### ISSUE TITLE
security concern:  user data should not be included in 'Data Import/Export'

### ISSUE THREAD

**Issue by maxlklaxl** [strawlab/neuron-catalog#35]
when downloading the data as json there is also the user db in there

**Comment by astraw** [comment]
It is intentional to supply information sufficient to create a mapping from `_id` to `username`. [This code](https://github.com/strawlab/neuron-catalog/blob/master/server/allow_and_startup.coffee#L47-51) ensures that no more than that is passed for all users.

For the currently logged in user, more details are indeed unintentionally being included in the JSON file for download, including the emails and encrypted, salted password. However, note that this information will always be in the user's browser and it is trivial to dump it from there. So my fix will be to prevent it from being saved, but this will just prevent users from shooting themselves in the foot rather than inherently preventing this data from reaching the user.
